### ISSUE TITLE
Wrong value in indexPvaff?

### ISSUE THREAD

**Issue by MindCartographer** [markheckmann/OpenRepGrid#28]
Hi Mark,

I think there is a significant mismatch between the value we get through indexPvaff and the one shown in the x axis of the biplot2d. An example below.

The value reported by RECORD 6 (GRIDCOR 6) matches the one in the biplot2d, so maybe the calculation behind indexPvaff should be reviewed. 
[Note: Gridcor 6 uses Correspondence Analysis instead of the ORG Principal Component Analysis]. 

![image](https://user-images.githubusercontent.com/65066036/81468994-f5299180-91e2-11ea-8e15-06774bf77e98.png)

![image](https://user-images.githubusercontent.com/65066036/81469057-3752d300-91e3-11ea-9b8a-66d7cb51b89b.png)

Thanks for your work,
José A. González Del Puerto
Psychology PhD Student

**Comment by markheckmann** [comment]
Dear José, 
thanks for your comments. `indexPvaff` was based on the SVD of the construct correlation matrix. I changed that to the PCA of the construct centered raw data as default method in this [commit](https://github.com/markheckmann/OpenRepGrid/commit/c5e2681310f570b925dbce2d4202c474377ea53d). The PVAFF value now matches the `biplot2d` output.  The old method is still available by setting `method = 2`.

Thanks a lot for your comments!

```
> file <-   ##"Sarah PRE - For R.xlsx"
> x <- importExcel(file)
> indexPvaff(x)
Note: As of v0.1.14 PVAFF is derived using PCA of the construct centered ratings by default. Before that the construct correlation matrix was used (see method=2).

[1] 0.4903784 
```
