### ISSUE TITLE
A cosmetic bug in the Implicative Dilemmas output

### ISSUE THREAD

**Issue by MindCartographer** [markheckmann/OpenRepGrid#29]
Dear Mark,

In the output of the indexDilemma function, the different constructs are classified corectly as "congruent", "discrepant" or "neither" ones. This is perfectly fine. The detection of the implicative dilemmas looks also correct, and matches, for instance, the resulsts in Gridcor 6. 

There is though a cosmetic bug related to the Ideal scores shown in the section "Classification of Constructs", that leads to funny readings and creates confusion. In the example below: first construct is classified as "discrepant" having apparently scores 1 and 3 (Self and Ideal, respectively; it looks like "neither"); the second construct is classified as "congruent" with scores 1 and 7 (it looks like "discrepant"), and so on.. Correct Ideal scores for these 2 first constructs should have been 5 and 1 instead of 3 and 7, as you can see in the snapshot from Gridcor 6.

It seems that in some cases the Ideal value is taken from the reversed construct (from the focussed grid?). Just a guess.

![image](https://user-images.githubusercontent.com/65066036/81472253-0e3c3d80-91f7-11ea-8e60-11c6f57914ef.png)

Classification of constructs in GRIDCOR 6:

![image](https://user-images.githubusercontent.com/65066036/81472283-375cce00-91f7-11ea-8c28-80ff90ba0164.png)

Again, thanks a lot.
José

**Comment by markheckmann** [comment]
Dear Jose, thanks for the bug report! The issue is fixed now and the results for Sarah appear identical to Gridcor 6. In the end, one line of code was missing, causing the ideal ratings not to get reversed before the output.
