### ISSUE TITLE
Function texts3d

### ISSUE THREAD

**Issue by JaquelineFonseca** [markheckmann/OpenRepGrid#42]
Hello, I'm trying to implement the biplot3d function (biplot3d(teste, x, texts = labels, adj = c(0.5, 0.5), cex = c.cex)). However, I encounter the error: "Error in texts3d(coords, texts = labels, adj = c(0.5, 0.5), cex = c.cex, :" and "text 5 contains unsupported character". How could I resolve this? Is there any material on the texts3d function?

**Comment by markheckmann** [comment]
@JaquelineFonseca: I am closing this issue. Please repoe  in case the issue remains.

**Comment by JaquelineFonseca** [comment]
Dear @markheckmann, I solved this question. My database is in Portuguese, I removed accent marks and worked in R. Thank you!

**Comment by markheckmann** [comment]
@JaquelineFonseca Great, glad to hear it works now.
