### ISSUE TITLE
JOSS Review: add community guidelines

### ISSUE THREAD

**Issue by rlbarter** [markheckmann/OpenRepGrid#43]
G'day Mark! 

I'm working on my review of OpenRepGrid for JOSS (https://github.com/openjournals/joss-reviews/issues/6918), and everything looks good in my checklist except for "**Community guidelines**: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support?"

If you could add some community guidelines when you have a chance, and let me know, and I'll be able to conclude my review.

**Comment by markheckmann** [comment]
Dear @rlbarter ,
thanks for your review and the issue. A contributing guideline exists under the package [docs page](https://docs.openrepgrid.org/CONTRIBUTING.html). As it might be hard to find it, I added a new [section to the README.md ](https://github.com/markheckmann/OpenRepGrid?tab=readme-ov-file#contributing-to-openrepgrid) which links to the page. Please let me know, if that works for you.

**Comment by rlbarter** [comment]
Looks perfect. Thanks @markheckmann. Great job on your package!
